#!/bin/bash
#SBATCH -J project_7b_cl
#SBATCH -A cs475-575
#SBATCH -p class
#SBATCH --gres=gpu:1
#SBATCH -o project_7b_cl.out
#SBATCH -e project_7b_cl.err
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=jeongju@oregonstate.edu

rm -rf cl_result.txt
rm -rf cl_sums_result.txt

echo "project 7b - autocorrelation using GPU OpenCL"
echo LOCAL_SIZE = 32
g++ -o opencl project_7b_cl.cpp /usr/local/apps/cuda/cuda-10.1/lib64/libOpenCL.so.1.1 -lm -fopenmp
./opencl
