#!/bin/bash
#SBATCH -J project_5_loop
#SBATCH -A cs475-575
#SBATCH -p class
#SBATCH --gres=gpu:1
#SBATCH -o project_5_loop.out
#SBATCH -e project_5_loop.err
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=jeongju@oregonstate.edu
for b in 16 32 64 128
do
echo BLOCKSIZE = $b
	for n in 16384 32768 65536 131072 262144 524288 1048576
	do
	echo NUMTRIALS = $n
	/usr/local/apps/cuda/cuda-10.1/bin/nvcc -DBLOCKSIZE=$b -DNUMTRIALS=$n -o loop project_5.cu
	./loop
	done
done