#!/bin/bash

#number of threads:
echo "Testing with various number of threads/n"
for t in 1 2 4 8
do
	for s in 50 100 300 500 700 1000 1500 2000 3000 5000
	do
		echo NUMNODES = $s
		g++ -DNUMNODES=$s -DNUMT=$t project_2.cpp -o prog -O3 -lm -fopenmp
		./prog
	done
done