#!/bin/bash

#number of threads:
echo "Testing with various number of threads/n"
for t in 1 2 4 8
do
	for s in 1 10 100 1000 10000 100000 200000 300000 400000 500000
	do
		echo NUMTRIALS = $s
		g++ -DNUMTRIALS=$s -DNUMT=$t project_1.cpp -o prog -O3 -lm -fopenmp
		./prog
	done
done